version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - golang_service

  golang_service:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: golang_service
    volumes:
      - ./go:/go/src
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=qwerqwer
      - DB_NAME=agnos_db
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerqwer
      POSTGRES_DB: agnos_db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
